queue_rules:
  - name: urgent
    queue_conditions:
      - label = urgent
    merge_conditions:
      - label = merge
  - name: <h1>dragondfdf</h1>
    queue_conditions:
      - label = standard
    merge_conditions:
      - label = merge
