queue_rules:
  - name: urgent
    queue_conditions:
      - label=urgent
    merge_conditions:
      - label=merge
  - name: <h1>test</test>
    queue_conditions:
      - label=<h1>test</h1>
    merge_condition:
      - label=merge
