queue_rules:
  - name: urgent
    queue_conditions:
      - label = urgent
    merge_conditions:
      - label = merge
  - name: standard
    queue_conditions:
      - label = standard
    merge_conditions:
      - label = merge